<?xml version="1.0" encoding="utf-8"?><Database Name="Certificado" Class="BancoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=certificate2016.copbpmix748w.us-west-2.rds.amazonaws.com,1433;Initial Catalog=Certificado;Persist Security Info=True;User ID=certvision" SettingsObjectName="Dal.Properties.Settings" SettingsPropertyName="CertificadoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Competidor" Member="Competidors">
    <Type Name="Competidor">
      <Column Name="PK_ID_COMPETIDOR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_FACEBOOK" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DT_NASCIMENTO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PONTOS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Faixa" Member="Faixas">
    <Type Name="Faixa">
      <Column Name="PK_ID_FAIXA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PONTOS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Lugar" Member="Lugars">
    <Type Name="Lugar">
      <Column Name="PK_ID_LUGAR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PONTOS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Modalidade" Member="Modalidades">
    <Type Name="Modalidade">
      <Column Name="PK_ID_MODALIDADE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PONTOS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tempo" Member="Tempos">
    <Type Name="Tempo">
      <Column Name="PK_ID_TEMPO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PONTOS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>