#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Certificado")]
	public partial class BancoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompetidor(Competidor instance);
    partial void UpdateCompetidor(Competidor instance);
    partial void DeleteCompetidor(Competidor instance);
    partial void InsertFaixa(Faixa instance);
    partial void UpdateFaixa(Faixa instance);
    partial void DeleteFaixa(Faixa instance);
    partial void InsertLugar(Lugar instance);
    partial void UpdateLugar(Lugar instance);
    partial void DeleteLugar(Lugar instance);
    partial void InsertModalidade(Modalidade instance);
    partial void UpdateModalidade(Modalidade instance);
    partial void DeleteModalidade(Modalidade instance);
    partial void InsertTempo(Tempo instance);
    partial void UpdateTempo(Tempo instance);
    partial void DeleteTempo(Tempo instance);
    #endregion
		
		public BancoDataContext() : 
				base(global::Dal.Properties.Settings.Default.CertificadoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Competidor> Competidors
		{
			get
			{
				return this.GetTable<Competidor>();
			}
		}
		
		public System.Data.Linq.Table<Faixa> Faixas
		{
			get
			{
				return this.GetTable<Faixa>();
			}
		}
		
		public System.Data.Linq.Table<Lugar> Lugars
		{
			get
			{
				return this.GetTable<Lugar>();
			}
		}
		
		public System.Data.Linq.Table<Modalidade> Modalidades
		{
			get
			{
				return this.GetTable<Modalidade>();
			}
		}
		
		public System.Data.Linq.Table<Tempo> Tempos
		{
			get
			{
				return this.GetTable<Tempo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Competidor")]
	public partial class Competidor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_COMPETIDOR;
		
		private string _NOME;
		
		private string _ID_FACEBOOK;
		
		private System.Nullable<System.DateTime> _DT_NASCIMENTO;
		
		private int _PONTOS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_COMPETIDORChanging(int value);
    partial void OnPK_ID_COMPETIDORChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnID_FACEBOOKChanging(string value);
    partial void OnID_FACEBOOKChanged();
    partial void OnDT_NASCIMENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_NASCIMENTOChanged();
    partial void OnPONTOSChanging(int value);
    partial void OnPONTOSChanged();
    #endregion
		
		public Competidor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_COMPETIDOR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_COMPETIDOR
		{
			get
			{
				return this._PK_ID_COMPETIDOR;
			}
			set
			{
				if ((this._PK_ID_COMPETIDOR != value))
				{
					this.OnPK_ID_COMPETIDORChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_COMPETIDOR = value;
					this.SendPropertyChanged("PK_ID_COMPETIDOR");
					this.OnPK_ID_COMPETIDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FACEBOOK", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ID_FACEBOOK
		{
			get
			{
				return this._ID_FACEBOOK;
			}
			set
			{
				if ((this._ID_FACEBOOK != value))
				{
					this.OnID_FACEBOOKChanging(value);
					this.SendPropertyChanging();
					this._ID_FACEBOOK = value;
					this.SendPropertyChanged("ID_FACEBOOK");
					this.OnID_FACEBOOKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_NASCIMENTO", DbType="Date")]
		public System.Nullable<System.DateTime> DT_NASCIMENTO
		{
			get
			{
				return this._DT_NASCIMENTO;
			}
			set
			{
				if ((this._DT_NASCIMENTO != value))
				{
					this.OnDT_NASCIMENTOChanging(value);
					this.SendPropertyChanging();
					this._DT_NASCIMENTO = value;
					this.SendPropertyChanged("DT_NASCIMENTO");
					this.OnDT_NASCIMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONTOS", DbType="Int NOT NULL")]
		public int PONTOS
		{
			get
			{
				return this._PONTOS;
			}
			set
			{
				if ((this._PONTOS != value))
				{
					this.OnPONTOSChanging(value);
					this.SendPropertyChanging();
					this._PONTOS = value;
					this.SendPropertyChanged("PONTOS");
					this.OnPONTOSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Faixa")]
	public partial class Faixa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_FAIXA;
		
		private string _DESCRICAO;
		
		private int _PONTOS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_FAIXAChanging(int value);
    partial void OnPK_ID_FAIXAChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnPONTOSChanging(int value);
    partial void OnPONTOSChanged();
    #endregion
		
		public Faixa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_FAIXA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_FAIXA
		{
			get
			{
				return this._PK_ID_FAIXA;
			}
			set
			{
				if ((this._PK_ID_FAIXA != value))
				{
					this.OnPK_ID_FAIXAChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_FAIXA = value;
					this.SendPropertyChanged("PK_ID_FAIXA");
					this.OnPK_ID_FAIXAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONTOS", DbType="Int NOT NULL")]
		public int PONTOS
		{
			get
			{
				return this._PONTOS;
			}
			set
			{
				if ((this._PONTOS != value))
				{
					this.OnPONTOSChanging(value);
					this.SendPropertyChanging();
					this._PONTOS = value;
					this.SendPropertyChanged("PONTOS");
					this.OnPONTOSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lugar")]
	public partial class Lugar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_LUGAR;
		
		private string _DESCRICAO;
		
		private int _PONTOS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_LUGARChanging(int value);
    partial void OnPK_ID_LUGARChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnPONTOSChanging(int value);
    partial void OnPONTOSChanged();
    #endregion
		
		public Lugar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_LUGAR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_LUGAR
		{
			get
			{
				return this._PK_ID_LUGAR;
			}
			set
			{
				if ((this._PK_ID_LUGAR != value))
				{
					this.OnPK_ID_LUGARChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_LUGAR = value;
					this.SendPropertyChanged("PK_ID_LUGAR");
					this.OnPK_ID_LUGARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONTOS", DbType="Int NOT NULL")]
		public int PONTOS
		{
			get
			{
				return this._PONTOS;
			}
			set
			{
				if ((this._PONTOS != value))
				{
					this.OnPONTOSChanging(value);
					this.SendPropertyChanging();
					this._PONTOS = value;
					this.SendPropertyChanged("PONTOS");
					this.OnPONTOSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modalidade")]
	public partial class Modalidade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_MODALIDADE;
		
		private string _DESCRICAO;
		
		private int _PONTOS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_MODALIDADEChanging(int value);
    partial void OnPK_ID_MODALIDADEChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnPONTOSChanging(int value);
    partial void OnPONTOSChanged();
    #endregion
		
		public Modalidade()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_MODALIDADE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_MODALIDADE
		{
			get
			{
				return this._PK_ID_MODALIDADE;
			}
			set
			{
				if ((this._PK_ID_MODALIDADE != value))
				{
					this.OnPK_ID_MODALIDADEChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_MODALIDADE = value;
					this.SendPropertyChanged("PK_ID_MODALIDADE");
					this.OnPK_ID_MODALIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONTOS", DbType="Int NOT NULL")]
		public int PONTOS
		{
			get
			{
				return this._PONTOS;
			}
			set
			{
				if ((this._PONTOS != value))
				{
					this.OnPONTOSChanging(value);
					this.SendPropertyChanging();
					this._PONTOS = value;
					this.SendPropertyChanged("PONTOS");
					this.OnPONTOSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tempo")]
	public partial class Tempo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_TEMPO;
		
		private string _DESCRICAO;
		
		private int _PONTOS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_TEMPOChanging(int value);
    partial void OnPK_ID_TEMPOChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnPONTOSChanging(int value);
    partial void OnPONTOSChanged();
    #endregion
		
		public Tempo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_TEMPO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_TEMPO
		{
			get
			{
				return this._PK_ID_TEMPO;
			}
			set
			{
				if ((this._PK_ID_TEMPO != value))
				{
					this.OnPK_ID_TEMPOChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_TEMPO = value;
					this.SendPropertyChanged("PK_ID_TEMPO");
					this.OnPK_ID_TEMPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONTOS", DbType="Int NOT NULL")]
		public int PONTOS
		{
			get
			{
				return this._PONTOS;
			}
			set
			{
				if ((this._PONTOS != value))
				{
					this.OnPONTOSChanging(value);
					this.SendPropertyChanging();
					this._PONTOS = value;
					this.SendPropertyChanged("PONTOS");
					this.OnPONTOSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
